import { Component, OnInit } from '@angular/core';
import { AlertController, ModalController, ToastController } from '@ionic/angular';
import { SettingItem, UserProfile, Vehicle } from '../data/models';
import { ParkingDataService } from '../services/parking-data.service';
import { GENERAL_SETTINGS, OTHER_SETTINGS } from '../data/app-settings';
import { AddVehicleModalComponent } from '../modal/add-vehicle/add-vehicle-modal.component';

@Component({
  selector: 'app-tab3',
  templateUrl: 'tab3.page.html',
  styleUrls: ['tab3.page.scss'],
  standalone: false,
})
export class Tab3Page implements OnInit {
  selectedSegment: 'dashboard' | 'list' = 'dashboard';

  userProfile: UserProfile = { name: '', phone: '', avatar: '', role: '' };
  vehicles: Vehicle[] = [];
  generalSettings = GENERAL_SETTINGS;
  otherSettings = OTHER_SETTINGS;

  constructor(
    private parkingService: ParkingDataService,
    private modalCtrl: ModalController,
    private toastCtrl: ToastController,
    private alertCtrl: AlertController // Add AlertController
  ) { }

  ngOnInit() {
    this.parkingService.userProfile$.subscribe(p => { if (p) this.userProfile = p; });
    this.parkingService.vehicles$.subscribe(v => {
      // Sort vehicles: Default vehicle first, then order by rank
      this.vehicles = [...v].sort((a, b) => {
        if (a.isDefault && !b.isDefault) return -1;
        if (!a.isDefault && b.isDefault) return 1;
        return (a.rank || 0) - (b.rank || 0);
      });
    });
  }

  segmentChanged(event: any) {
    this.selectedSegment = event.detail.value;
  }

  async selectVehicle(vehicleId: number | string) {
    const selectedCar = this.vehicles.find(v => v.id === vehicleId);
    if (!selectedCar || selectedCar.isDefault) return; // Prevent re-selecting the same car

    const alert = await this.alertCtrl.create({
      header: 'ตั้งเป็นยานพาหนะหลัก',
      message: `คุณต้องการตั้งรถทะเบียน <strong>${selectedCar.licensePlate}</strong> เป็นยานพาหนะหลักหรือไม่?`,
      buttons: [
        {
          text: 'ยกเลิก',
          role: 'cancel',
          cssClass: 'text-gray-500'
        },
        {
          text: 'ยืนยัน',
          role: 'confirm',
          handler: async () => {
            try {
              await this.parkingService.setDefaultVehicle(vehicleId);
              this.showToast('ตั้งค่าเป็นยานพาหนะหลักเรียบร้อย', 'success');
            } catch (e) {
              this.showToast('เกิดข้อผิดพลาด ไม่สามารถตั้งค่าได้', 'error');
            }
          }
        }
      ]
    });

    await alert.present();
  }

  async addVehicle() {
    if (this.vehicles.length >= 3) {
      await this.showToast('ไม่สามารถเพิ่มยานพาหนะได้ เนื่องจากถึงขีดจำกัด 3 คันแล้ว', 'error');
      return;
    }

    const modal = await this.modalCtrl.create({
      component: AddVehicleModalComponent,
      breakpoints: [0, 0.85, 1],
      initialBreakpoint: 0.85,
      cssClass: 'add-vehicle-modal'
    });

    await modal.present();

    const { data, role } = await modal.onDidDismiss();

    if (role === 'confirm' && data) {
      if (this.vehicles.length >= 3) {
        await this.showToast('ไม่สามารถเพิ่มยานพาหนะได้ เนื่องจากถึงขีดจำกัด 3 คันแล้ว', 'error');
        return;
      }

      // Assign ID and Rank here or in service (Service handles ID mostly but let's be safe)
      const newVehicle: Partial<Vehicle> = {
        ...data,
        // id is generated by DB
        rank: this.vehicles.length + 1
      };

      console.log('[Tab3Page] Submitting new vehicle:', newVehicle);

      try {
        await this.parkingService.addVehicle(newVehicle);
        console.log('[Tab3Page] Vehicle added workflow complete');

        await this.showToast('เพิ่มยานพาหนะสำเร็จเรียบร้อย', 'success');

      } catch (error) {
        console.error('[Tab3Page] Failed to add vehicle:', error);
        await this.showToast('เกิดข้อผิดพลาด ไม่สามารถเพิ่มยานพาหนะได้', 'error');
      }
    }
  }

  async editVehicle(vehicle: Vehicle) {
    const modal = await this.modalCtrl.create({
      component: AddVehicleModalComponent,
      breakpoints: [0, 0.85, 1],
      initialBreakpoint: 0.85,
      cssClass: 'add-vehicle-modal',
      componentProps: {
        editVehicle: vehicle
      }
    });

    await modal.present();

    const { data, role } = await modal.onDidDismiss();

    if (role === 'confirm' && data) {
      console.log('[Tab3Page] Submitting edited vehicle:', data);
      try {
        // Need to pass full Vehicle type if editing
        const editedVehicle = {
          ...vehicle, // fallback
          ...data
        } as Vehicle;

        // Ensure parkingService has an updateVehicle method taking the updated data  
        // In local state it's updateVehicle, maybe need backend call updateVehicle in service if real
        await this.parkingService.updateVehicle(editedVehicle);
        console.log('[Tab3Page] Vehicle edit workflow complete');

        await this.showToast('แก้ไขข้อมูลยานพาหนะสำเร็จเรียบร้อย', 'success');

      } catch (error) {
        console.error('[Tab3Page] Failed to edit vehicle:', error);
        await this.showToast('เกิดข้อผิดพลาด ไม่สามารถแก้ไขยานพาหนะได้', 'error');
      }
    }
  }

  async showToast(message: string, type: 'success' | 'error' = 'success') {
    const icon = type === 'success' ? 'checkmark-circle' : 'alert-circle';
    const cssClass = type === 'success' ? 'custom-toast success-toast' : 'custom-toast error-toast';

    const toast = await this.toastCtrl.create({
      message: message,
      duration: 3000,
      position: 'top',
      cssClass: cssClass,
      icon: icon,
      buttons: [
        {
          icon: 'close',
          role: 'cancel',
          handler: () => {
            console.log('Close clicked');
          }
        }
      ]
    });
    await toast.present();
  }

  getLicensePlateParts(plate: string): string[] {
    return plate ? plate.split(' ') : ['', ''];
  }
}



